main:
    rm -r ../newBackEnd/public/public
    cp -r ../application/public ../newBackEnd/public/public
    cp ../newBackEnd/public/public/index.html ../newBackEnd/public/public/index2.html
    rm ../newBackEnd/public/public/index.html
    